### ISSUE TITLE
Emphasive recursive tests

### ISSUE THREAD

**Issue by MylesBorins** [scottcorgan/tap-spec#18]
Lets say you had the following test

``` js
var test = require('tape');
test('I am on the outside', function (t) {
  t.test('I am on the inside', function (tt) {
    tt.ok(true, 'All done!');
    t.end();
    tt.end();
  });
});

```

You will get the output

```
  1) I am on the outside


  2) I am on the inside

    ✓ All done!
```

Should it not be

```
  1) I am on the outside

      • I am on the inside

            ✓ All done!
```

**Comment by gyzerok** [comment]
Do we have any progress for this here with this module?
I definitely love tape. But I'm really frustrated with current output for nested tests.

**Comment by scottcorgan** [comment]
@gyzerok Are you using tape or tap? Tape doesn't output formatted subtests but tap does.

**Comment by gyzerok** [comment]
@scottcorgan I am using tape but now I guess would switch to tap. Thank you!

**Comment by chrisfrancis27** [comment]
Just stumbled across this thread - my solution for nested tests was to not actually write nested tests, but conform to a convention with my test names to use consistent delimiters for namespacing, e.g. `"Foo controller: someMethod(): When given a set of args"`.

This is then parsed (in [this commit on my fork of tap-spec](https://github.com/chrisfrancis27/tap-spec/commit/96f897243dc7fc4f6ae02b4c7aa5560268b855d6)) to the following:

    Foo controller
        someMethod()
            When given a set of args
                ✔ returns 200 OK
                ✔ returns all tags

Not the most elegant, I know, but it means not having to use nested tests, which is [apparently not recommended](https://github.com/substack/tape/issues/184).
