### ISSUE TITLE
no colors when installed with -g

### ISSUE THREAD

**Issue by yoshuawuyts** [scottcorgan/tap-spec#23]
Don't think I'm doing something odd with my terminal, but welp: I don't see any colors when installed with `-g`.

**Comment by scottcorgan** [comment]
Can you post a screenshot of what you see?

**Comment by yoshuawuyts** [comment]
Wish I could post a screenshot, but the issue is with a product that's locked down :( The screenshot wouldn't be exciting though, it's just regular `tap-spec` output but sans the colors.

**Comment by scottcorgan** [comment]
I am unable to reproduce. What OS is this on and which terminal application are you using?

**Comment by yoshuawuyts** [comment]
OS X yosemite with `iterm2`.

**Comment by yoshuawuyts** [comment]
Derp, I suspect this is caused by [`watch`](http://ghub.io/watch). Derp, sorry for the fuss.

**Comment by scottcorgan** [comment]
Glad it worked out. Let me know if you need anything for this module.

**Comment by yoshuawuyts** [comment]
Will do. Thanks for your time!
