### ISSUE TITLE
Error while trying to run from local node_modules (not global)

### ISSUE THREAD

**Issue by nelsonic** [scottcorgan/tap-spec#25]
When attempting to run `tape | tap-spec` using the *relative* (**not** *globally* installed) module:
```sh 
node node_modules/tape/bin/tape test/*.js | node_modules/tap-spec/bin/cmd.js
```
I'm getting the following error: **Error: Cannot find module 'isarray'**
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'isarray'
```
![tap-spec-error](https://cloud.githubusercontent.com/assets/194400/6094351/d9e95876-af1e-11e4-9615-49d204584c6c.png)

I *manually* `npm install isarray` and then I get the error: **Error: Cannot find module 'core-util-is'**

![tap-spec-error-2](https://cloud.githubusercontent.com/assets/194400/6094361/4f71dbfe-af1f-11e4-85de-fb72d5956a71.png)

After I install **core-util-is** with `npm install --save-dev core-util-is` the command works:

![tap-spec-works-with-dependencies-installed](https://cloud.githubusercontent.com/assets/194400/6094367/8daea992-af1f-11e4-8de3-e54129650c7a.png)

@scottcorgan can I submit a PR adding these two modules to your package.json as **devDependencies**? *thanks*

**Comment by nelsonic** [comment]
**#ignore** I deleted **node_modules** and re-installed everything and it works as expected.

**Comment by nelsonic** [comment]
Thanks again for nice formatter for Tape/Tap! :+1:

**Comment by IrenaMcG** [comment]
thanks, this helped me ;)

**Comment by ElenaShevchenko** [comment]
Thank you very much, your solution help me
