### ISSUE TITLE
handle assert.skip

### ISSUE THREAD

**Issue by scottcorgan** [scottcorgan/tap-spec#26]

**Comment by hville** [comment]
This would be really nice since future test get hidden as passed. Unfortunately, it looks like the 'tap-out' parser doesn't support it out of the box. Would you consider another parser (eg. tap-parser) or did you already had a plan on how to go about this?

**Comment by shime** [comment]
:+1:

**Comment by scottcorgan** [comment]
What does your unformatted TAP output look like when you skip a test?

**Comment by shime** [comment]
yeah, sorry about that... found out this is related to tape, so it should probably wait until https://github.com/substack/tape/pull/197 lands

**Comment by scottcorgan** [comment]
Will keep open until that's addressed in tape

**Comment by keithamus** [comment]
FYI @scottcorgan I've added some details in `tap-out` about TODO and SKIP tests - see https://github.com/scottcorgan/tap-out/issues/16
