### ISSUE TITLE
Loss of expected/actual information

### ISSUE THREAD

**Issue by domenic** [scottcorgan/tap-spec#29]
With the default TAP output of tape, I get things like 

```
not ok 44 the readable stream's pull should have been called twice
  ---
    operator: equal
    expected: 2
    actual:   1
  ...
```

with tap-spec, I only get 

```
    × the readable stream's pull should have been called twice
```

**Comment by scottcorgan** [comment]
My initial thoughts is that this information to be grouped with the errors at the bottom of the output. Any objections?

**Comment by domenic** [comment]
That seems pretty reasonable :)

**Comment by tomekwi** [comment]
:+1:

By the way, the version 0.2.1 displays all info alongside:

```
    ✗ is a function
     ---
       operator: equal
       expected: 'function'
       actual:   'object'
       at: Test.<anonymous> (/home/tomek/Web/tomekwi/stereo/test.js:6:6)
     ...
```

**Comment by tomekwi** [comment]
I really find the way tap-spec 2 handles things convenient. Summary of failed tests at the bottom. Extended info and console output inline with the tests, but nicely yellowed out.

It’s great to keep the tail concise. I see what fails on the first sight. When I want to find out more, I just scroll upwards.

I try to write my tests first, so I often end up with umpteen failures one after another. Having all that info at the tail would be visual clutter.

**Comment by scottcorgan** [comment]
You make a good point. I was thinking about putting all the tail
information online with the failed spec output.

I'll think about it more and decide what works best.

**Comment by shinnn** [comment]
Totally agree with @tomekwi .

**Comment by tnguyen14** [comment]
@scottcorgan You said that the information would be grouped at the bottom of output. That is not supported in the current release, correct? Any way to get that information with the current version of tap-spec?

**Comment by ro-ka** [comment]
I can confirm that it is not shown in the current version (`3.0.0`).

**Comment by lxe** [comment]
Also confirming that the assertion expected/actual data isn't displayed in 3.0.0. The failure summary isn't displayed at the bottom either, like it was in 2.x.

**Comment by grit96** [comment]
Can confirm expected/actual is not displayed in version `3.0.0`. This is something that would be very useful.

**Comment by scottcorgan** [comment]
`4.0.0` coming out today. Adds back `2.x` output. Sorry about that everyone.

**Comment by scottcorgan** [comment]
The line number and character column information provided by packages like `tape` weren't always accurate. This made that information unhelpful and provided too much information on the error output.

`4.0.0` adds back the inlined raw TAP error output immediately following the failed spec title.

**Comment by tomekwi** [comment]
Hi @scottcorgan, thanks for tackling this problem :)

I’ve just done a hands-on test. All in all it looks great! I really like the way the failed spec is red, underlined and easy to spot when scrolling:

![image](https://cloud.githubusercontent.com/assets/4624660/7888710/cf9f4cb8-063a-11e5-9f47-09d60c062df2.png)

The only thing I noticed is that I don’t see custom `console.log` output between the specs, like I did in *tap-spec 2.x*. Have you hidden it on purpose, or is it just not ready yet?

**Comment by tomekwi** [comment]
Actually, there seems to be a problem with that as well. The `actual` part is lost – here’s how the same spec looked in *v2*:

![image](https://cloud.githubusercontent.com/assets/4624660/7888826/93bf2faa-063b-11e5-96f5-684f5406d58b.png)

**Comment by scottcorgan** [comment]
@tomekwi I didn't remove it on purpose. The underlying tap parser treats `console.log()` like a comment and I didn't realize that I didn't implement comments when I switched from [tap-parser](https://github.com/substack/tap-parser) to [tap-out](https://github.com/scottcorgan/tap-out).

I'd be open to a PR if you'd like. I have to jump on some other projects at the moment now.

**Comment by tomekwi** [comment]
> I'd be open to a PR if you'd like. I have to jump on some other projects at the moment now.

I hope I can squeeze it in next week. I’m also quite tied up with work.

Thanks again, anyway @scottcorgan :)

**Comment by tomekwi** [comment]
Do you want to reopen this issue or shall I open a new one?

**Comment by scottcorgan** [comment]
Probably a good idea to open a new one.

Possibly describe what you're looking for as opposed to the current output.

**Comment by tomekwi** [comment]
Yes sir!

**Comment by tomekwi** [comment]
* #33
* #34
