### ISSUE TITLE
Format object printing in error output

### ISSUE THREAD

**Issue by scottcorgan** [scottcorgan/tap-spec#32]
Convert raw tap error output to readable output, especially for deepEqual comparisons

**Comment by vvo** [comment]
That.would.be.awesome! Congrats on the recent work on tap-spec, I have been able to re-add it on my projects

**Comment by scottcorgan** [comment]
@vvo:

I have been working on a collection of packages under the org [tap-format](https://github.com/tap-format) as sequels to my few [tap-[formatter]](https://github.com/search?utf8=%E2%9C%93&q=repo%3Ascottcorgan%2Ftap-spec+repo%3Ascottcorgan%2Ftap-dot+repo%3Ascottcorgan%2Ftap-out&type=Repositories&ref=searchresults) modules.

https://github.com/tap-format/spec will be the replacement for this. It's basically done, just needs documentation and screenshots/video-gifs.

**Comment by vvo** [comment]
thanks!

**Comment by romseguy** [comment]
What's the status on this? I'd like to contribute but your last message makes me wonder whether you already started implementing this or not.
