### ISSUE TITLE
Comments between specs are lost (v4.0.0)

### ISSUE THREAD

**Issue by tomekwi** [scottcorgan/tap-spec#33]
Raw *tape* output:

![image](https://cloud.githubusercontent.com/assets/4624660/7889119/bcdbcf90-063d-11e5-8cd0-08e5c434eba2.png)

Here’s how *tap-spec 2.x* handled it:

![image](https://cloud.githubusercontent.com/assets/4624660/7889154/fd19690a-063d-11e5-98c5-aa4c7cd55ce3.png)

And here’s what happens in *tap-spec v4.0.0*:

![image](https://cloud.githubusercontent.com/assets/4624660/7889175/2cdabcfc-063e-11e5-9bf5-c4e5e4f5a1ef.png)

It would be great to have the log message back.

**Comment by scottcorgan** [comment]
Have you tried using [`t.comment()`](https://github.com/substack/tape#tcommentmessage) ?

**Comment by tomekwi** [comment]
Yup, but that ends up showing like a title of a group of specs.

Besides, these `console.log` calls are usually temporary and in code, outside the test function – so I don’t even have access to `t.comment()`.

**Comment by scottcorgan** [comment]
Is this still an issue for you in `4.0.0`?

**Comment by tomekwi** [comment]
Yes, that was an issue with 4.0.0 from the very beginning:

> And here’s what happens in tape v4.0.0: […] It would be great to have the log message back.

I still use v2. I actually want to help you out but can’t find the time.

**Comment by scottcorgan** [comment]
Published as `4.0.2`. Sorry for the delay.

**Comment by tomekwi** [comment]
:+1: Thanks a lot! :D
