### ISSUE TITLE
check for thrown exception upstream and exit 1

### ISSUE THREAD

**Issue by scottcorgan** [scottcorgan/tap-spec#40]

**Comment by markuswustenberg** [comment]
We just got bitten by this, thinking our test suite succeeded when in fact tests had syntax errors. Cool that there's an issue tracking this already. :) @scottcorgan Any ETA? I may get time to look at it myself, although I don't know the tap-spec code base (yet).

**Comment by scottcorgan** [comment]
@markuswustenberg I'm not an stdout/stdin specialist so I've been unable to fix this yet. It's very annoying and shouldn't happen. Any input or suggestions are VERY much welcome!

**Comment by scottcorgan** [comment]
Fixed! And released as `4.1.1`. Many thanks to @jamestalmage for fix on https://github.com/scottcorgan/tap-out/pull/18

**Comment by jamestalmage** [comment]
:+1:
