### ISSUE TITLE
exit 1 on successful test run

### ISSUE THREAD

**Issue by brianleroux** [scottcorgan/tap-spec#42]
tap-spec@4.1.1 exit 1
tap-spec@4.0.0 exit 0

tests are supa vanilla tap output!

:grimacing:

**Comment by scottcorgan** [comment]
Can you post your unformatted tap output?

**Comment by scottcorgan** [comment]
@brianleroux:

I have been working on a collection of packages under the org [tap-format](https://github.com/tap-format) as sequels to my few [tap-[formatter]](https://github.com/search?utf8=%E2%9C%93&q=repo%3Ascottcorgan%2Ftap-spec+repo%3Ascottcorgan%2Ftap-dot+repo%3Ascottcorgan%2Ftap-out&type=Repositories&ref=searchresults) modules.

https://github.com/tap-format/spec will be the replacement for this. It's basically done, just needs documentation and screenshots/video-gifs.
