### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [scottcorgan/tap-spec#46]
Would you please consider creating a LICENSE file with your copyright information and the text of the MIT license?  The MIT license specifically states that the license text must accompany the source code.  (If you'd prefer, I'd be happy to do this as a pull request -- just respond back to this issue with your copyright information.)

**Comment by scottcorgan** [comment]
Good idea. Done in https://github.com/scottcorgan/tap-spec/commit/8ce610dc87cfe81764f411ed7f980577298f7885
