### ISSUE TITLE
Output doesn't display negative numbers

### ISSUE THREAD

**Issue by andremw** [scottcorgan/tap-spec#48]
One of my tests are supposed to display the results like this:

✔ -1 days remaining: quality is 0

But it's being displayed without the hyphen:
✔ 1 days remaining: quality is 0

The negative number is displayed properly when I do not use tap-spec.

I tried to debug and the string is fine until **through**'s index.js line 36:

`stream.emit('data', data)`
data is `"ok 19 -1 days remaining: quality is 0\n"` which is correct.

The data is fine here, just as I expected, but whoever is catching this 'data' event is removing the hyphen.. I'm opening this issue here as it's not happening when I use standard output.

**Comment by scottcorgan** [comment]
Is this still an issue?

**Comment by scottcorgan** [comment]
Closing from inactivity
