### ISSUE TITLE
@tap-format/spec vs. tap-spec

### ISSUE THREAD

**Issue by thisconnect** [scottcorgan/tap-spec#49]
Are you going to move this in favor of @tap-format/spec ?

new?
https://github.com/tap-format/spec
https://www.npmjs.com/package/@tap-format/spec

legacy?
https://github.com/scottcorgan/tap-spec

**Comment by scottcorgan** [comment]
Yes, the goals is that the parser under tap-format and the renderers will be the _next_ versions of `tap-spec` and `tap-out` respectively.

I just haven't had time to go through and add examples and update READMEs.

I'll keep this open because it's a good indicator of my intentions.

**Comment by thisconnect** [comment]
Thanks @scottcorgan !!
What do you recommend to use today? @tap-format/spec or tap-spec

**Comment by scottcorgan** [comment]
@tap-format/spec has a nicer output, so I'd stick with that.

I am open for PRs to add docs, etc. to help get that library some attention.

**Comment by thisconnect** [comment]
I just ran into the issue that both reporters swallowed a TypeError stack see

https://github.com/substack/tape/issues/365

**Comment by scottcorgan** [comment]
@thisconnect I really want to fix the problem with swallowing errors, but I just don't have time right now. Would you want to take a look?

**Comment by thisconnect** [comment]
After this week I should (hopefully) have more time too. I could try and maybe find out where exactly things go wrong. Should I rather look at @tap-format/spec or tap-spec?

**Comment by scottcorgan** [comment]
I guess start with `tap-spec`, and if it's obvious, take a look elsewhere.

**Comment by thisconnect** [comment]
ping @scottcorgan not sure about if this is great, but it's a start please review https://github.com/scottcorgan/tap-out/pull/29/files
