### ISSUE TITLE
Exit code on failure

### ISSUE THREAD

**Issue by vespakoen** [scottcorgan/tap-spec#52]
I would expect tap-spec to produce a non-zero exit code when 1 or more test fail.
It looks like this is not the case at the moment and my CI system marks the tests as passing.

**Comment by scottcorgan** [comment]
Do you have example TAP output to reproduce?

**Comment by vespakoen** [comment]
Here's what I've got:

```
TAP version 13
# hello world
not ok 1 A and B should not be equal
ok 2 A and A should be equal

1..2
# tests 2
# pass 1

# not ok
```

**Comment by vespakoen** [comment]
Ahh, looks like my code is not emitting `# fail  1` =)

Closing...

**Comment by vespakoen** [comment]
Note, the `# fail 1` was not the problem, I think the `# not ok` or not having the description of the error was causing it.
