### ISSUE TITLE
module size???

### ISSUE THREAD

**Issue by MegaArman** [scottcorgan/tap-spec#54]
I can't help but point out that this module is over 2x the size of the Tape module itself (2.2M vs 980k). I'm not sure if tap-spec is still being maintained at this point, but for all considering using this module - be aware it includes all of Lodash.

**Comment by scottcorgan** [comment]
It is still being maintained. I'd be open to a PR to make the bundle smaller. 👍 

I personally haven't had any issues with the size, but my use cases may be different.

**Comment by MegaArman** [comment]
Oh nice, thanks for the reply Scott. I'll try to open a PR today or tomorrow.

**Comment by scottcorgan** [comment]
I'm going to close this issue, be we can continue the discussion. Because this is a module that can be cached locally, I'm not super worried about the size of the bundle just yet.
