### ISSUE TITLE
tap-spec CLI will succeed even when tests are catastrophically aborted

### ISSUE THREAD

**Issue by lxe** [scottcorgan/tap-spec#56]
If the command that pipes TAP output to tap-spec cpi catastrophically fails with some ELIFECYCLE without printing that a test failure occurs, tap-spec will not register the error, and exit with successful status code. 

This makes something like this dengerous:

```json
"scripts": {
  "test": "npm run do-the-test | tap-spec"
}
```

if `npm run do-the-test` fails, tap-spec will succeed, making `npm test` succeed.

> NOTE: This is true to most pipe-based commands passed to npm without set -o pipefail or something of the sort, but it's especially bad for test runners.

For example:

```
$ (cat <<EOF && false) | ./node_modules/.bin/tap-spec ; echo exit code is $?
TAP version 13
1..1
# Test The Thing
ok 1 - Thing is OK
ERROR! A CATASTROPHIC FAILURE 
TESTS ABORTED
EOF
```

Will print:

```

  Test The Thing

    ✔ Thing is OK
    ERROR! A CATASTROPHIC FAILURE
    TESTS ABORTED


  total:     1
  passing:   1
  duration:  8ms


exit code is 0
```

Which is not what we want. 

Doing something like "set -o pipefail && npm run do-the-test | tap-spec" will sort of work, if execution shell is `bash`, but it's not portable

**Comment by scottcorgan** [comment]
Thanks for opening the issue. I think it is a known issue, but I haven't really had time to investigate a solution.

For now, have you tried https://github.com/tap-format/spec? It was originally developed to be the successor to this library, but I haven't had time to make that official.

**Comment by scottcorgan** [comment]
This should be resolved by https://github.com/scottcorgan/tap-spec/commit/484f694b4d5f9953f2388687cb291993026b1cbb
