### ISSUE TITLE
Support more YAML features?

### ISSUE THREAD

**Issue by pawamoy** [scottcorgan/tap-spec#57]
It seems only a few things are supported within the YAML blocks. I guess this is because this formatter was only designed to work with `tape`.

I would like `tap-spec` to consume and format YAML blocks with multiline strings, like:

```tap
TAP version 13
# Software Architecture
ok 1 Complete Mediation
ok 2 Economy of Mechanism (ALLOWED FAILURE)
ok 3 Layered Architecture
not ok 4 Least Common Mechanism
  ---
  messages: |
    Dependencies to archan.logging (6) > matrix size (11) / independence factor (5) = 2.2
    Dependencies to archan.printing (4) > matrix size (11) / independence factor (5) = 2.2
  hint: Reduce number of modules having dependencies to the listed module.
  ...
# Open Design
ok 5 Infrastructure
ok 6 Source Code
# Pylint
ok 7 Code Clean (ALLOWED FAILURE)
1..7
```

Or nested items, like:

```tap
TAP version 13
# Software Architecture
ok 1 Complete Mediation
ok 2 Economy of Mechanism (ALLOWED FAILURE)
ok 3 Layered Architecture
not ok 4 Least Common Mechanism
  ---
  messages:
    - Dependencies to archan.logging (6) > matrix size (11) / independence factor (5) = 2.2
    - Dependencies to archan.printing (4) > matrix size (11) / independence factor (5) = 2.2
  hint: Reduce number of modules having dependencies to the listed module.
  ...
# Open Design
ok 5 Infrastructure
ok 6 Source Code
# Pylint
ok 7 Code Clean (ALLOWED FAILURE)
1..7
```

With that kind of data, `tap-spec` will stop consuming things after something it doesn't support (here, right after `ok 3 Layered Architecture`).

I don't know what is the current state about what is supported or not by `tap-spec`, is there some documentation about this?

**Comment by scottcorgan** [comment]
I agree, that would be a great addition. I originally planned for https://github.com/tap-format/spec to be the successor to tap-spec, and it does indeed work much better, including Yaml support. But, I haven't had time to document it and keep things up to date.

I am, however, open to a PR for this 👍

**Comment by pawamoy** [comment]
Nobody seems interested, closing :slightly_smiling_face:
